version: '3'
services:
  app:
    container_name: front-party-rent
    image: node:16-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install && yarn dev"
    # command: sh -c "npm install && npm run dev"
    ports:
      - '3000:3000'
